package com.Session;
// Generated 23 mars 2022, 15:21:43 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Achat generated by hbm2java
 */
@Entity
@Table(name = "achat", catalog = "agence_immobiliere")
public class Achat implements java.io.Serializable {

	private AchatId id;
	private Client client;
	private Facture facture;
	private ModeReglmt modeReglmt;
	private Proprietes proprietes;
	private int montant;
	private Date date;

	public Achat() {
	}

	public Achat(AchatId id, Client client, Facture facture, ModeReglmt modeReglmt, Proprietes proprietes, int montant,
			Date date) {
		this.id = id;
		this.client = client;
		this.facture = facture;
		this.modeReglmt = modeReglmt;
		this.proprietes = proprietes;
		this.montant = montant;
		this.date = date;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPropriete", column = @Column(name = "id_propriete", nullable = false)),
			@AttributeOverride(name = "idClient", column = @Column(name = "id_client", nullable = false)),
			@AttributeOverride(name = "idachat", column = @Column(name = "idachat", nullable = false)) })
	public AchatId getId() {
		return this.id;
	}

	public void setId(AchatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_client", nullable = false, insertable = false, updatable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_facture", nullable = false)
	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "code_paiement", nullable = false)
	public ModeReglmt getModeReglmt() {
		return this.modeReglmt;
	}

	public void setModeReglmt(ModeReglmt modeReglmt) {
		this.modeReglmt = modeReglmt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_propriete", nullable = false, insertable = false, updatable = false)
	public Proprietes getProprietes() {
		return this.proprietes;
	}

	public void setProprietes(Proprietes proprietes) {
		this.proprietes = proprietes;
	}

	@Column(name = "montant", nullable = false)
	public int getMontant() {
		return this.montant;
	}

	public void setMontant(int montant) {
		this.montant = montant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
