package com.Session;
// Generated 23 mars 2022, 15:21:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AchatId generated by hbm2java
 */
@Embeddable
public class AchatId implements java.io.Serializable {

	private int idPropriete;
	private int idClient;
	private int idachat;

	public AchatId() {
	}

	public AchatId(int idPropriete, int idClient, int idachat) {
		this.idPropriete = idPropriete;
		this.idClient = idClient;
		this.idachat = idachat;
	}

	@Column(name = "id_propriete", nullable = false)
	public int getIdPropriete() {
		return this.idPropriete;
	}

	public void setIdPropriete(int idPropriete) {
		this.idPropriete = idPropriete;
	}

	@Column(name = "id_client", nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idachat", nullable = false)
	public int getIdachat() {
		return this.idachat;
	}

	public void setIdachat(int idachat) {
		this.idachat = idachat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AchatId))
			return false;
		AchatId castOther = (AchatId) other;

		return (this.getIdPropriete() == castOther.getIdPropriete()) && (this.getIdClient() == castOther.getIdClient())
				&& (this.getIdachat() == castOther.getIdachat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPropriete();
		result = 37 * result + this.getIdClient();
		result = 37 * result + this.getIdachat();
		return result;
	}

}
