package com.Session;
// Generated 23 mars 2022, 15:21:43 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "agence_immobiliere")
public class Adresse implements java.io.Serializable {

	private Integer numAdresse;
	private String rue;
	private String ville;
	private Set<Proprietes> proprieteses = new HashSet<Proprietes>(0);

	public Adresse() {
	}

	public Adresse(String rue, String ville) {
		this.rue = rue;
		this.ville = ville;
	}

	public Adresse(String rue, String ville, Set<Proprietes> proprieteses) {
		this.rue = rue;
		this.ville = ville;
		this.proprieteses = proprieteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "num_adresse", unique = true, nullable = false)
	public Integer getNumAdresse() {
		return this.numAdresse;
	}

	public void setNumAdresse(Integer numAdresse) {
		this.numAdresse = numAdresse;
	}

	@Column(name = "rue", nullable = false, length = 10)
	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	@Column(name = "ville", nullable = false, length = 10)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Proprietes> getProprieteses() {
		return this.proprieteses;
	}

	public void setProprieteses(Set<Proprietes> proprieteses) {
		this.proprieteses = proprieteses;
	}

}
