package com.Session;
// Generated 23 mars 2022, 15:21:43 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModeReglmt generated by hbm2java
 */
@Entity
@Table(name = "mode_reglmt", catalog = "agence_immobiliere")
public class ModeReglmt implements java.io.Serializable {

	private Integer codePaiement;
	private String libelle;
	private Set<Achat> achats = new HashSet<Achat>(0);

	public ModeReglmt() {
	}

	public ModeReglmt(String libelle) {
		this.libelle = libelle;
	}

	public ModeReglmt(String libelle, Set<Achat> achats) {
		this.libelle = libelle;
		this.achats = achats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "code_paiement", unique = true, nullable = false)
	public Integer getCodePaiement() {
		return this.codePaiement;
	}

	public void setCodePaiement(Integer codePaiement) {
		this.codePaiement = codePaiement;
	}

	@Column(name = "libelle", nullable = false, length = 20)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeReglmt")
	public Set<Achat> getAchats() {
		return this.achats;
	}

	public void setAchats(Set<Achat> achats) {
		this.achats = achats;
	}

}
