package com.Session;
// Generated 23 mars 2022, 15:21:43 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proprietaire generated by hbm2java
 */
@Entity
@Table(name = "proprietaire", catalog = "agence_immobiliere")
public class Proprietaire implements java.io.Serializable {

	private Integer idProprietaire;
	private String nom;
	private String prenom;
	private String civilite;
	private int telephone;
	private Set<Proprietes> proprieteses = new HashSet<Proprietes>(0);

	public Proprietaire() {
	}

	public Proprietaire(String nom, String prenom, String civilite, int telephone) {
		this.nom = nom;
		this.prenom = prenom;
		this.civilite = civilite;
		this.telephone = telephone;
	}

	public Proprietaire(String nom, String prenom, String civilite, int telephone, Set<Proprietes> proprieteses) {
		this.nom = nom;
		this.prenom = prenom;
		this.civilite = civilite;
		this.telephone = telephone;
		this.proprieteses = proprieteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_proprietaire", unique = true, nullable = false)
	public Integer getIdProprietaire() {
		return this.idProprietaire;
	}

	public void setIdProprietaire(Integer idProprietaire) {
		this.idProprietaire = idProprietaire;
	}

	@Column(name = "nom", nullable = false, length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 20)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "civilite", nullable = false, length = 20)
	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	@Column(name = "telephone", nullable = false)
	public int getTelephone() {
		return this.telephone;
	}

	public void setTelephone(int telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proprietaire")
	public Set<Proprietes> getProprieteses() {
		return this.proprieteses;
	}

	public void setProprieteses(Set<Proprietes> proprieteses) {
		this.proprieteses = proprieteses;
	}

}
