package com.Session;
// Generated 23 mars 2022, 15:21:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VisiterId generated by hbm2java
 */
@Embeddable
public class VisiterId implements java.io.Serializable {

	private int idPropriete;
	private int idClient;

	public VisiterId() {
	}

	public VisiterId(int idPropriete, int idClient) {
		this.idPropriete = idPropriete;
		this.idClient = idClient;
	}

	@Column(name = "id_propriete", nullable = false)
	public int getIdPropriete() {
		return this.idPropriete;
	}

	public void setIdPropriete(int idPropriete) {
		this.idPropriete = idPropriete;
	}

	@Column(name = "id_client", nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VisiterId))
			return false;
		VisiterId castOther = (VisiterId) other;

		return (this.getIdPropriete() == castOther.getIdPropriete()) && (this.getIdClient() == castOther.getIdClient());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPropriete();
		result = 37 * result + this.getIdClient();
		return result;
	}

}
