package com.Paiement;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

import com.Session.ModeReglmt;
import com.reglemt.ReglementDAO;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class paiementController implements Initializable{
	@FXML
	private TextField idfacture;
	@FXML
	private TextField date;
	@FXML
	private TextField montant;
	@FXML
	private Button valide;
	@FXML
	private ComboBox paiement;

	// Event Listener on Button[#valide].onAction
	@FXML
	public void valideon(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		List<ModeReglmt> reglement = null;
		ReglementDAO mode = new ReglementDAO();
		reglement = mode.getMode();
		ObservableList< String>  regler = FXCollections.observableArrayList();
		for (ModeReglmt modeReglmt : reglement) {
			regler.add(modeReglmt.getLibelle());
		}
		paiement.setItems(regler);
			
	}
}
